"""Lua addon forge — turn an IntentSpec into a working Lua file.

The in-game UI gathers a player's intent (job, weapons,
modes, food, lockstyle, etc.), validates it, then calls
the forge to render it into a working Lua addon. Output
is deterministic — same spec → byte-identical lua.

The forge handles all 12 addon shapes the
addon_template_registry knows about. For shapes the
forge can't render natively (a brand-new shape a modder
adds), the caller can register a custom renderer.

This module owns the GearSwap renderer in detail because
that's the marquee case (Tart's RDM.lua reference). Other
shapes get a small skeleton renderer that the AI engine
fills in via the LLM hook (caller-injected).

Public surface
--------------
    ForgeOutput dataclass (frozen)
    ForgeError dataclass (frozen)
    LuaAddonForge
        .render(spec, shape) -> ForgeOutput | ForgeError
        .register_renderer(shape, fn) -> bool
        .render_gearswap(spec) -> str   (direct GearSwap path)
"""
from __future__ import annotations

import dataclasses
import typing as t

from server.addon_intent_spec import (
    AddonIntentSpec, GearSetEntry, validate,
)
from server.addon_template_registry import (
    AddonShape, AddonTemplateRegistry, default_registry,
)


@dataclasses.dataclass(frozen=True)
class ForgeOutput:
    success: bool
    addon_id: str
    shape: AddonShape
    lua_source: str
    line_count: int


@dataclasses.dataclass(frozen=True)
class ForgeError:
    success: bool
    reason: str
    spec_errors: tuple[str, ...]


def _quote(s: str) -> str:
    """Lua double-quote with escaping."""
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _render_gear_set(name: str, entry: GearSetEntry) -> str:
    """Render one sets.X = { slot=item, ... } table."""
    if not entry.slot_to_item:
        return f"\tsets.{name} = {{}}\n"
    lines = [f"\tsets.{name} = {{"]
    # Stable slot order for reproducible output
    for slot in sorted(entry.slot_to_item.keys()):
        item = entry.slot_to_item[slot]
        lines.append(f"\t\t{slot}={_quote(item)},")
    lines.append("\t}\n")
    return "\n".join(lines)


def _render_gearswap(spec: AddonIntentSpec) -> str:
    """Render a GearSwap-style Lua file from an IntentSpec.

    Mirrors the canonical RDM.lua structure: header
    constants, jobsetup call, get_sets() with weapon
    sets, idle set, offense modes.
    """
    out: list[str] = []
    out.append("-- Auto-generated by Demoncore Lua Forge")
    out.append(f"-- Addon: {spec.addon_id}")
    out.append(f"-- Job:   {spec.job}")
    out.append("")
    if spec.lockstyle_pallet:
        out.append(f"LockStylePallet = {_quote(spec.lockstyle_pallet)}")
    if spec.macro_book:
        out.append(f"MacroBook = {_quote(spec.macro_book)}")
    if spec.macro_set:
        out.append(f"MacroSet = {_quote(spec.macro_set)}")
    if spec.food_item:
        out.append(f"Food = {_quote(spec.food_item)}")
    out.append("")
    if spec.offense_modes:
        mode_names = ", ".join(
            _quote(m.mode_name) for m in spec.offense_modes
        )
        out.append(
            f"state.OffenseMode:options({mode_names})"
        )
        if spec.default_offense_mode:
            out.append(
                f"state.OffenseMode:set("
                f"{_quote(spec.default_offense_mode)})"
            )
    out.append("")
    out.append("function get_sets()")
    out.append("\tsets.Weapons = {}")
    # Weapon sets — sorted for stable diffs
    for set_name in sorted(spec.weapon_sets.keys()):
        entry = spec.weapon_sets[set_name]
        out.append(_render_gear_set(
            f"Weapons[{_quote(set_name)}]", entry,
        ))
    if spec.idle_set:
        out.append(_render_gear_set("Idle", spec.idle_set))
    out.append("end")
    out.append("")
    return "\n".join(out)


def _render_simple_skeleton(
    spec: AddonIntentSpec, shape: AddonShape,
) -> str:
    """Render a stub for shapes without full renderers.

    The AI engine (LLM) is expected to flesh these out;
    this skeleton gives it a structured starting point
    rather than a blank file.
    """
    out: list[str] = []
    out.append("-- Auto-generated by Demoncore Lua Forge")
    out.append(f"-- Addon: {spec.addon_id}")
    out.append(f"-- Shape: {shape.value}")
    out.append("")
    out.append(
        "-- Forge skeleton — handler functions to implement:"
    )
    out.append("function on_load() end")
    out.append("function on_unload() end")
    out.append("function on_event(event_name, payload) end")
    out.append("")
    return "\n".join(out)


_RendererFn = t.Callable[[AddonIntentSpec], str]


@dataclasses.dataclass
class LuaAddonForge:
    _registry: AddonTemplateRegistry = dataclasses.field(
        default_factory=default_registry,
    )
    _renderers: dict[AddonShape, _RendererFn] = dataclasses.field(
        default_factory=dict,
    )

    def register_renderer(
        self, *, shape: AddonShape, fn: _RendererFn,
    ) -> bool:
        if shape in self._renderers:
            return False
        self._renderers[shape] = fn
        return True

    def render(
        self, *, spec: AddonIntentSpec, shape: AddonShape,
    ) -> t.Union[ForgeOutput, ForgeError]:
        # Spec validation gate — bad specs never produce code.
        v = validate(spec)
        if not v.valid:
            return ForgeError(
                success=False,
                reason="spec_invalid",
                spec_errors=v.errors,
            )
        # Required-field check from the template registry.
        manifest = self._registry.lookup(shape=shape)
        if manifest is None:
            return ForgeError(
                success=False,
                reason="unknown_shape",
                spec_errors=(),
            )
        # Pick the renderer.
        if shape == AddonShape.GEARSWAP:
            source = _render_gearswap(spec)
        elif shape in self._renderers:
            source = self._renderers[shape](spec)
        else:
            source = _render_simple_skeleton(spec, shape)
        return ForgeOutput(
            success=True,
            addon_id=spec.addon_id,
            shape=shape,
            lua_source=source,
            line_count=source.count("\n") + 1,
        )

    def render_gearswap(
        self, *, spec: AddonIntentSpec,
    ) -> str:
        return _render_gearswap(spec)


__all__ = [
    "ForgeOutput", "ForgeError", "LuaAddonForge",
]
